language: android
jdk: oraclejdk8

env:
  global:
   - ANDROID_API_LEVEL=26
   - ANDROID_BUILD_TOOLS_VERSION=27.0.3

android:
  components:
    - tools
    - platform-tools
    - tools
    - android-$ANDROID_API_LEVEL
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
  - cd android 
  - chmod +x gradlew

script:
  - ./gradlew assembleDebug  
